name: Deploy GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Pages beállítása
        uses: actions/configure-pages@v5

      - name: Docs mappa feltöltése
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Publikálás GitHub Pages-re
        id: deployment
        uses: actions/deploy-pages@v4
